[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

[rpc_endpoints]
scroll = "https://rpc.scroll.io"
scroll-sepolia = "https://scroll-sepolia.drpc.org"

[etherscan]
scroll = { key = "${SCROLLSCAN_API_KEY}", url = "https://api.scrollscan.com/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
